In [13]:
import pandas as pd

df = pd.read_csv("../data/citibike_weather_daily.csv",parse_dates=["ride_date"])

df.head()

,ride_date,num_rides,avg_duration_min,temp_f,max_temp_f,min_temp_f,wind_speed_knots,precip_in,day_of_week,month
0,2013-07-01,16650,16.309988,74.8,78.1,73.4,7.8,0.00,Monday,7
1,2013-07-02,22745,15.968826,76.1,82.9,73.0,8.0,0.73,Tuesday,7
2,2013-07-03,21864,16.238808,78.5,84.9,73.9,8.8,0.06,Wednesday,7
3,2013-07-04,22326,21.218474,82.0,91.0,73.9,8.6,0.96,Thursday,7
4,2013-07-05,21842,18.040443,84.4,93.0,75.9,9.0,0.00,Friday,7

In [17]:
df["year"] = df["ride_date"].dt.year
df["month"] = df["ride_date"].dt.month
df["day_of_week"] = df["ride_date"].dt.dayofweek
df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)

df.head()

,ride_date,num_rides,avg_duration_min,temp_f,max_temp_f,min_temp_f,wind_speed_knots,precip_in,day_of_week,month,year,is_weekend
0,2013-07-01,16650,16.309988,74.8,78.1,73.4,7.8,0.00,0,7,2013,0
1,2013-07-02,22745,15.968826,76.1,82.9,73.0,8.0,0.73,1,7,2013,0
2,2013-07-03,21864,16.238808,78.5,84.9,73.9,8.8,0.06,2,7,2013,0
3,2013-07-04,22326,21.218474,82.0,91.0,73.9,8.6,0.96,3,7,2013,0
4,2013-07-05,21842,18.040443,84.4,93.0,75.9,9.0,0.00,4,7,2013,0

In [18]:
df.columns

Index(['ride_date', 'num_rides', 'avg_duration_min', 'temp_f', 'max_temp_f',
       'min_temp_f', 'wind_speed_knots', 'precip_in', 'day_of_week', 'month',
       'year', 'is_weekend'],
      dtype='object')

In [19]:
#Check to for any errors in the data set 
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

In [20]:
X = df.drop(columns=["ride_date", "num_rides"])
y = df["num_rides"]

In [21]:
#Verify the removal of ride_date and num_rides
print(X.head())
print(y.head())

   avg_duration_min  temp_f  max_temp_f  min_temp_f  wind_speed_knots  \
0         16.309988    74.8        78.1        73.4               7.8
1         15.968826    76.1        82.9        73.0               8.0
2         16.238808    78.5        84.9        73.9               8.8
3         21.218474    82.0        91.0        73.9               8.6
4         18.040443    84.4        93.0        75.9               9.0

   precip_in  day_of_week  month  year  is_weekend
0       0.00            0      7  2013           0
1       0.73            1      7  2013           0
2       0.06            2      7  2013           0
3       0.96            3      7  2013           0
4       0.00            4      7  2013           0
0    16650
1    22745
2    21864
3    22326
4    21842
Name: num_rides, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (1288, 10)
X_test: (322, 10)
y_train: (1288,)
y_test: (322,)